# Generated by Django 2.0 on 2020-01-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='media/capa/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
