# Generated by Django 2.0 on 2020-02-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0002_auto_20200129_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
